### ISSUE TITLE
Navigator.withRoot(rootScreen)

### ISSUE THREAD

**Issue by jmfayard** [wealthfront/magellan#41]
Hello, how to best handle the scenario where the first screen shown to the user can vary?

For example if the user

1. is not registered yet, show her a registration screen
2. comes from a notification, open a screen corresponding to the data inside the notification
3. Or maybe in the instrumentation tests, I want to tell the activity directly what screen it should first open

I tried to have two different Activities, with each having its navigator, but that does not seem how I'm supposed to use Magellan.

Or do you create a `RootScreen()` that has no UX at all but immediately replace herself with whatever screen make sense depending on the state of the world?

   jm

**Comment by fabiendevos** [comment]
The best way is to simply put that logic in your main Activity, using `rewriteHistory()`, or `resetWithRoot()`
Here is an example:

In MainActivity's onCreate(), before calling `navigator.onCreate()`
```java
if (authenticator.isLoggedOut()) {
      navigator.resetWithRoot(this, loginScreen);
}
```

With `rewriteHistory()` it's more powerful: you can pass an arbitrary function to put the backstack in whatever state you want.

When you want to touch the backstack *after* calling `navigator.onCreate()` (`navigator.onCreate()` is called for you by SingleActivity if you're using it), then you need to use `navigate(historyRewriter)` because it's technically a navigation event (it won't animate by default so the user won't notice though). This is done that way only to make sure `onShow()` and `onHide()` are kept in balance.
